apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
spec:
  selector:
    app: devops-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 5009
    targetPort: 5009
    nodePort: 30090
